In [6]:
import pandas as pd

In [8]:
df = pd.read_csv('data.csv')

In [9]:
df


Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [10]:
import numpy as np

In [11]:
np.__version__

'1.20.3'

In [13]:
df.index

RangeIndex(start=0, stop=11914, step=1)

In [74]:
df.mode()

Make           Model  Year  Engine Fuel Type  Engine HP  \
0  Chevrolet  Silverado 1500  2015  regular unleaded      200.0   

   Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0               4.0         AUTOMATIC  front wheel drive              4.0   

  Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
0       Crossover      Compact         Sedan           24        17   

   Popularity  MSRP  
0        1385  2000

In [20]:

df[df.Make == 'Ford']

Make     Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
1331   Ford  Aerostar  1995  regular unleaded      135.0               6.0   
1332   Ford  Aerostar  1995  regular unleaded      135.0               6.0   
1333   Ford  Aerostar  1995  regular unleaded      155.0               6.0   
1334   Ford  Aerostar  1995  regular unleaded      135.0               6.0   
1335   Ford  Aerostar  1996  regular unleaded      140.0               6.0   
...     ...       ...   ...               ...        ...               ...   
11443  Ford  Windstar  2003  regular unleaded      200.0               6.0   
11444  Ford  Windstar  2003  regular unleaded      200.0               6.0   
11445  Ford  Windstar  2003  regular unleaded      200.0               6.0   
11446  Ford  Windstar  2003  regular unleaded      200.0               6.0   
11447  Ford  Windstar  2003  regular unleaded      200.0               6.0   

      Transmission Type      Driven_Wheels  Number of Doors Market Category  \
1331          AUTOMATIC   rear wheel drive              3.0             NaN   
1332          AUTOMATIC   rear wheel drive              3.0             NaN   
1333          AUTOMATIC    all wheel drive              3.0             NaN   
1334          AUTOMATIC   rear wheel drive              3.0             NaN   
1335          AUTOMATIC   rear wheel drive              3.0             NaN   
...                 ...                ...              ...             ...   
11443         AUTOMATIC  front wheel drive              4.0             NaN   
11444         AUTOMATIC  front wheel drive              4.0             NaN   
11445         AUTOMATIC  front wheel drive              4.0             NaN   
11446         AUTOMATIC  front wheel drive              4.0             NaN   
11447         AUTOMATIC  front wheel drive              4.0             NaN   

      Vehicle Size      Vehicle Style  highway MPG  city mpg  Popularity  \
1331       Midsize      Cargo Minivan           22        16        5657   
1332       Midsize  Passenger Minivan           22        15        5657   
1333         Large  Passenger Minivan           18        14        5657   
1334         Large  Passenger Minivan           22        15        5657   
1335       Midsize  Passenger Minivan           21        15        5657   
...            ...                ...          ...       ...         ...   
11443      Midsize  Passenger Minivan           22        16        5657   
11444      Midsize  Passenger Minivan           22        16        5657   
11445      Midsize  Passenger Minivan           22        16        5657   
11446      Midsize  Passenger Minivan           22        16        5657   
11447      Midsize  Passenger Minivan           22        16        5657   

        MSRP  
1331    2000  
1332    2000  
1333    2000  
1334    2000  
1335    2000  
...      ...  
11443  23070  
11444  26315  
11445  29230  
11446  34825  
11447  31835  

[881 rows x 16 columns]

In [27]:
df[df.Make == 'Toyota']

Make    Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
479    Toyota  4Runner  2014  regular unleaded      270.0               6.0   
480    Toyota  4Runner  2014  regular unleaded      270.0               6.0   
481    Toyota  4Runner  2014  regular unleaded      270.0               6.0   
482    Toyota  4Runner  2014  regular unleaded      270.0               6.0   
483    Toyota  4Runner  2014  regular unleaded      270.0               6.0   
...       ...      ...   ...               ...        ...               ...   
11827  Toyota    Yaris  2017  regular unleaded      106.0               4.0   
11828  Toyota    Yaris  2017  regular unleaded      106.0               4.0   
11829  Toyota    Yaris  2017  regular unleaded      106.0               4.0   
11830  Toyota    Yaris  2017  regular unleaded      106.0               4.0   
11831  Toyota    Yaris  2017  regular unleaded      106.0               4.0   

      Transmission Type      Driven_Wheels  Number of Doors Market Category  \
479           AUTOMATIC   rear wheel drive              4.0             NaN   
480           AUTOMATIC   rear wheel drive              4.0             NaN   
481           AUTOMATIC   four wheel drive              4.0             NaN   
482           AUTOMATIC   four wheel drive              4.0             NaN   
483           AUTOMATIC   four wheel drive              4.0             NaN   
...                 ...                ...              ...             ...   
11827            MANUAL  front wheel drive              2.0       Hatchback   
11828         AUTOMATIC  front wheel drive              4.0       Hatchback   
11829         AUTOMATIC  front wheel drive              4.0       Hatchback   
11830         AUTOMATIC  front wheel drive              4.0       Hatchback   
11831            MANUAL  front wheel drive              4.0       Hatchback   

      Vehicle Size  Vehicle Style  highway MPG  city mpg  Popularity   MSRP  
479        Midsize        4dr SUV           23        17        2031  41365  
480        Midsize        4dr SUV           23        17        2031  35740  
481        Midsize        4dr SUV           22        17        2031  37615  
482        Midsize        4dr SUV           22        17        2031  34695  
483        Midsize        4dr SUV           22        17        2031  35725  
...            ...            ...          ...       ...         ...    ...  
11827      Compact  2dr Hatchback           36        30        2031  15250  
11828      Compact  4dr Hatchback           35        30        2031  16375  
11829      Compact  4dr Hatchback           35        30        2031  17285  
11830      Compact  4dr Hatchback           35        30        2031  18000  
11831      Compact  4dr Hatchback           36        30        2031  17200  

[746 rows x 16 columns]

In [81]:
df[df.Make == 'Audi'].Model.nunique()

34

In [36]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [46]:
df["Engine Cylinders"].mode()

0    4.0
dtype: float64

In [53]:
df["Engine Cylinders"].median()

6.0

In [73]:
df["Engine Cylinders"].fillna(4.0).median()

6.0

In [103]:
lotus_cars = df[df.Make == "Lotus"]

In [108]:
lotus_cars = lotus_cars[['Engine HP', 'Engine Cylinders']].drop_duplicates()

In [109]:
lotus_cars

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [110]:
X = lotus_cars.values

In [111]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [112]:
XTX = X.T.dot(X)

In [113]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [115]:
XTX_inv = np.linalg.inv(XTX)

In [116]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [120]:
w = XTX_inv.dot(X.T).dot(y)

In [121]:
w

array([  4.59494481, -63.56432501])